name: Deploy Portal (namgun.or.kr)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull latest code
        run: |
          cd /mnt/d/Docker/namgun-workspace
          git fetch origin main
          git reset --hard origin/main

      - name: Build and deploy (portal mode)
        run: |
          cd /mnt/d/Docker/namgun-workspace
          docker compose -f docker-compose.yml -f docker-compose.portal.yml up -d --build

      - name: Health check
        run: |
          echo "Waiting for services to start..."
          for i in $(seq 1 10); do
            if curl -sf --max-time 5 http://localhost:8000/api/health; then
              echo ""
              echo "Deploy successful (attempt $i)"
              exit 0
            fi
            echo "Attempt $i failed, retrying in 5s..."
            sleep 5
          done
          echo "Health check failed after 10 attempts"
          exit 1
